// livro-servidor/clientes/livros-react/src/App.tsx
import {BrowserRouter, NavLink, Route, Routes} from "react-router-dom"
import "./App.css"
import LivroLista from "./LivroLista"
import LivroDados from "./LivroDados"

function App() {
    return (
        <BrowserRouter>
            <nav className="navbar bg-dark navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
                <div className="container-fluid">
                    <div className="collapse navbar-collapse">
                        <ul className="navbar-nav">
                            <li className="nav-item">
                                <NavLink to="/" className={"nav-link"}>
                                    Catálogo
                                </NavLink>
                            </li>
                            <li className="nav-item">
                                <NavLink to="/dados" className={"nav-link"}>
                                    Novo
                                </NavLink>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
            <Routes>
                <Route path="/" element={<LivroLista />} />
                <Route path="dados" element={<LivroDados />} />
            </Routes>
        </BrowserRouter>
    )
}

export default App

// livro-servidor/clientes/livros-angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterOutlet } from '@angular/router';
import { LivroListaComponent } from "./livro-lista/livro-lista.component";
import { LivroDadosComponent } from './livro-dados/livro-dados.component';

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
  imports: [RouterOutlet,RouterLink]
})
export class AppComponent {
  title = 'livros-angular';
}

<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content below * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced.  * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * Delete the template below * * * * * * * * * -->
<!-- * * * * * * * to get started with your project! * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->

<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav">
        <li class="nav-item m-2">
          <a class=" nav-item m-2 text-light link-underline-opacity-0"style="text-decoration-line: none;" routerLink="/lista"
            >Catálogo</a
          >
        </li>
        <li class="nav-item m-2">
          <a class="text-light link-underline-opacity-0"style="text-decoration-line: none;" routerLink="/dados">Novo</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container mt-4">
  <router-outlet></router-outlet>
</div>

<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * The content above * * * * * * * * * * * * -->
<!-- * * * * * * * * * * is only a placeholder * * * * * * * * * * * -->
<!-- * * * * * * * * * * and can be replaced.  * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
<!-- * * * * * * * * * * End of Placeholder  * * * * * * * * * * * * -->
<!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * -->
