// livro-servidor/clientes/livros-react/src/LivroLista.js
import {useEffect, useState} from "react"
import {ControleEditora} from "./controle/ControleEditora"
import {ControleLivro} from "./controle/ControleLivros"

export default function LivroLista() {
    var controlador = new ControleLivro()
    var editoras = new ControleEditora()

    function LinhaLivro(props) {
        const nomeEditora = editoras.getNomeEditora(props.codEditora)
        return (
            <tr key={`${props._id}`}>
                <td style={{height: "100px"}}>{props.titulo}</td>
                <td style={{height: "100px"}}>{props.resumo}</td>
                <td style={{height: "100px"}}>{nomeEditora}</td>
                <td style={{height: "100px"}}>
                    <ul>
                        {props.autores.map((autor, index) => (
                            <li key={index}>{autor}</li>
                        ))}
                    </ul>
                </td>
                <td className="align-self-stretch align-middle">
                    <button
                        className="btn btn-danger btn-sm"
                        onClick={() => {
                            controlador.excluir(props._id).then(() => {
                                setCarregado(false)
                            })
                        }}
                    >
                        Excluir
                    </button>
                </td>
            </tr>
        )
    }

    const [livros, setLivros] = useState([])
    const [carregado, setCarregado] = useState(false)

    useEffect(() => {
        controlador.obterLivros().then((livros) => {
            setLivros(livros)
            setCarregado(true)
        })
    }, [carregado])

    return (
        <main className="p-4">
            <h1>Catálogo de Livros</h1>
            <table className="table table-striped">
                <thead className="table-dark">
                    <tr>
                        <th scope="col">Título</th>
                        <th scope="col">Resumo</th>
                        <th scope="col">Editora</th>
                        <th scope="col">Autores</th>
                        <th scope="col"></th>
                    </tr>
                </thead>
                <tbody>
                    {livros.length > 0 ? (
                        livros.map((livro, index) => <LinhaLivro key={index} {...livro} index={index} />)
                    ) : (
                        <tr>
                            <td colSpan="5" className="text-center">
                                Nenhum livro encontrado
                            </td>
                        </tr>
                    )}
                </tbody>
            </table>
        </main>
    )
}

// livro-servidor/clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component } from '@angular/core';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { NgFor } from '@angular/common';
import { Router } from '@angular/router';

@Component({
  selector: 'app-livro-lista',
  standalone: true,
  imports: [NgFor],
  templateUrl: './livro-lista.component.html',
  styleUrl: './livro-lista.component.css'
})
export class LivroListaComponent {
  editoras: Editora[] = [];
  livros: Livro[] = [];

  constructor(private servEditora: ControleEditoraService, private servLivros: ControleLivrosService, private router: Router) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros().then((livros) => {
      this.livros = livros
    })
  }

  excluir = (codigo: string): void => {
    this.servLivros.excluir(codigo).then(()=>{
      this.servLivros.obterLivros().then((livros) => {
        this.livros = livros
      })
    })
  }

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora);
  }
}

<!-- livro-lista.component.html -->

<main class="container">
  <h1>Catálogo de Livros</h1>

  <table class="table table-striped">
    <thead >
      <tr class="table-dark">
        <th scope="col">Título</th>
        <th scope="col">Resumo</th>
        <th scope="col">Editora</th>
        <th scope="col">Autores</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td>{{ livro.titulo }}</td>
        <td>{{ livro.resumo }}</td>
        <td>{{ obterNome(livro.codEditora) }}</td>
        <td>
          <ul>
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
        <td>
          <button class="btn btn-danger" (click)="excluir(livro.codigo)">
            Excluir
          </button>
        </td>
      </tr>
    </tbody>
  </table>
</main>
