// livro-servidor/clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component } from '@angular/core';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { NgFor } from '@angular/common';
import { Router } from '@angular/router';

@Component({
  selector: 'app-livro-lista',
  standalone: true,
  imports: [NgFor],
  templateUrl: './livro-lista.component.html',
  styleUrl: './livro-lista.component.css'
})
export class LivroListaComponent {
  editoras: Editora[] = [];
  livros: Livro[] = [];

  constructor(private servEditora: ControleEditoraService, private servLivros: ControleLivrosService, private router: Router) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.servLivros.obterLivros().then((livros) => {
      this.livros = livros
    })
  }

  excluir = (codigo: string): void => {
    this.servLivros.excluir(codigo).then(()=>{
      this.servLivros.obterLivros().then((livros) => {
        this.livros = livros
      })
    })
  }

  obterNome = (codEditora: number): string => {
    return this.servEditora.getNomeEditora(codEditora);
  }
}

<!-- livro-lista.component.html -->

<main class="container">
  <h1>Catálogo de Livros</h1>

  <table class="table table-striped">
    <thead >
      <tr class="table-dark">
        <th scope="col">Título</th>
        <th scope="col">Resumo</th>
        <th scope="col">Editora</th>
        <th scope="col">Autores</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td>{{ livro.titulo }}</td>
        <td>{{ livro.resumo }}</td>
        <td>{{ obterNome(livro.codEditora) }}</td>
        <td>
          <ul>
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
        <td>
          <button class="btn btn-danger" (click)="excluir(livro.codigo)">
            Excluir
          </button>
        </td>
      </tr>
    </tbody>
  </table>
</main>

// livro-servidor/clientes/livros-next/pages/LivroLista.tsx
import {useState, useEffect} from "react"
import Head from "next/head"
import {Menu} from "../componentes/Menu"
import {LinhaLivro} from "../componentes/LinhaLivro"
import {ControleLivro, LivroMongo} from "../classes/controle/ControleLivros"

interface Livro {
    codigo: string | null
    titulo: string
    resumo: string
    codEditora: number
    autores: string[]
}

const LivroLista: React.FC = () => {
    const [livros, setLivros] = useState<Livro[]>([])
    const [carregado, setCarregado] = useState<boolean>(false)

    const controleLivros = new ControleLivro()

    const excluirLivro = (codigo: string) => {
        controleLivros.excluir(codigo).then(() => {
            setCarregado(false)
        })
    }

    useEffect(() => {
        const fetchData = async () => {
            controleLivros.obterLivros().then((livrosMongo: LivroMongo[]) => {
                const livros: Livro[] = livrosMongo.map((livroMongo) => ({
                    codigo: livroMongo._id,
                    titulo: livroMongo.titulo,
                    resumo: livroMongo.resumo,
                    codEditora: livroMongo.codEditora,
                    autores: livroMongo.autores,
                }))
                setLivros(livros)
                setCarregado(true)
            })
        }
        fetchData()
    }, [carregado])

    return (
        <div>
            <Head>
                <title>Livro Lista</title>
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Menu />
            <main className="px-5">
                <h1>Catálogo de Livros</h1>
                <table className="table table-striped">
                    <thead className="table-dark">
                        <tr>
                            <th scope="col">Título</th>
                            <th scope="col">Resumo</th>
                            <th scope="col">Editora</th>
                            <th scope="col">Autores</th>
                            <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {livros.map((livro) => (
                            <LinhaLivro key={livro.codigo} livro={livro} excluir={() => excluirLivro(livro.codigo as string)} />
                        ))}
                    </tbody>
                </table>
            </main>
        </div>
    )
}

export default LivroLista
