// livro-servidor/clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component } from '@angular/core';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';
import { ControleEditoraService } from '../controle-editora.service';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { NgFor } from '@angular/common';
import { FormsModule} from '@angular/forms';

@Component({
  selector: 'app-livro-dados',
  standalone: true,
  imports: [NgFor, FormsModule],
  templateUrl: './livro-dados.component.html',
  styleUrl: './livro-dados.component.css'
})
export class LivroDadosComponent {
  livro: Livro;
  autoresForm: string = '';
  editoras: Editora[] = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) { this.livro = new Livro(0, 0, '', '', [this.autoresForm]) }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split('\n'); 
    this.livro.codEditora = Number(this.livro.codEditora)
    this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista');
  }

}

<main class="container">
  <h1>Dados do Livro</h1>
  <form (submit)="incluir()" ngNativeValidate>
    <div class="mb-2">
      <label class="form-label" for="titulo">Título</label>
      <input
        type="text"
        class="form-control"
        id="titulo"
        required
        [(ngModel)]="livro.titulo"
        name="titulo"
      />
    </div>
    <div class="mb-2">
      <label class="form-label" for="resumo">Resumo</label>
      <textarea
        class="form-control"
        id="resumo"
        rows="3"
        [(ngModel)]="livro.resumo"
        name="resumo"
      ></textarea>
    </div>
    <div class="mb-2">
      <label class="form-label" for="editora">Editora</label>
      <select
        class="form-select"
        id="editora"
        required
        [(ngModel)]="livro.codEditora"
        name="editora"
      >
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">
          {{ editora.nome }}
        </option>
      </select>
    </div>
    <div class="mb-2">
      <label class="form-label" for="autores">Autores (1 por linha)</label>
      <textarea
        class="form-control"
        id="autores"
        rows="3"
        [(ngModel)]="autoresForm"
        name="autores"
      ></textarea>
    </div>
    <button type="submit" class="btn btn-primary">Salvar Dados</button>
  </form>
</main>

// livro-servidor/clientes/livros-next/pages/LivroDados.tsx
import {useState} from "react"
import Head from "next/head"
import {useRouter} from "next/router"
import {ControleEditora} from "../classes/controle/ControleEditora"
import {Menu} from "../componentes/Menu"
import {Livro} from "../classes/modelo/Livro"
import {ControleLivro, LivroMongo} from "../classes/controle/ControleLivros"

const controleEditora = new ControleEditora()
const controleLivros = new ControleLivro()

const LivroDados: React.FC = () => {
    const [titulo, setTitulo] = useState<string>("")
    const [resumo, setResumo] = useState<string>("")
    const [autores, setAutores] = useState<string>("")
    const [codEditora, setCodEditora] = useState<string>("0")

    const opcoes = controleEditora.getEditoras().map((editora) => ({value: String(editora.codEditora), text: editora.nome}))

    const navigate = useRouter().push

    const incluirLivro = async (livro: any): Promise<boolean> => {
        const response = await controleLivros.incluir(livro)
        return response
    }

    const tratarCombo = (e: React.ChangeEvent<HTMLSelectElement>) => {
        setCodEditora(e.target.value)
    }

    const incluir = async (e: React.FormEvent<HTMLFormElement>) => {
        e.preventDefault()
        const livro = {
            titulo,
            resumo,
            autores: autores.split("\n"),
            codEditora: Number(codEditora),
        }
        const sucesso = await incluirLivro(livro)
        if (sucesso) {
            navigate("/LivroLista")
        } else {
            console.error("Falha ao incluir o livro")
        }
    }

    return (
        <div>
            <Head>
                <title>Livro Dados</title>
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Menu />

            <main className="px-5">
                <h1>Dados do Livro</h1>
                <form onSubmit={incluir}>
                    <div className="mb-2">
                        <label className="form-label" htmlFor="titulo">
                            Título
                        </label>
                        <input
                            className="form-control"
                            type="text"
                            id="titulo"
                            value={titulo}
                            onChange={(event) => setTitulo(event.target.value)}
                        />
                    </div>
                    <div className="mb-2">
                        <label className="form-label" htmlFor="resumo">
                            Resumo
                        </label>
                        <textarea
                            className="form-control"
                            id="resumo"
                            draggable={false}
                            value={resumo}
                            onChange={(event) => setResumo(event.target.value)}
                        />
                    </div>
                    <div className="mb-2">
                        <label className="form-label" htmlFor="editora">
                            Editora
                        </label>
                        <select className="form-select" id="editora" value={codEditora} onChange={tratarCombo}>
                            {opcoes.map((opcao) => (
                                <option key={opcao.value} value={opcao.value}>
                                    {opcao.text}
                                </option>
                            ))}
                        </select>
                    </div>
                    <div className="mb-2">
                        <label className="form-label" htmlFor="autores">
                            Autores (1 por linha)
                        </label>
                        <textarea
                            className="form-control"
                            id="autores"
                            draggable={false}
                            value={autores}
                            onChange={(event) => setAutores(event.target.value)}
                        />
                    </div>

                    <button className="btn btn-primary" type="submit">
                        Salvar Dados
                    </button>
                </form>
            </main>
        </div>
    )
}

export default LivroDados
